

exports.DialerStatus = {
	ATTEMPT: 'dialer.attempt', // MEANS THAT A CALL ATEMPT HAS BEGAN
	SUCCESS: 'dialer.success', // MEANS THAT A CALL WAS SUCCESSFULLY ACCOMPLISHED
	FAILURE: 'dialer.failure', // MEANS THAT A CALL WAS BUSY, UNAVAILABLE
	EXPIRED: 'dialer.expired', // MEANS THAT TIME TO LIVE EXPIRED
	EXCEEDED: 'dialer.exceeded', // MEANS THAT A CALL HAS REACHED MAXIMUM ATTEMPTS
};